### ISSUE TITLE
Need a way to implement independent x/y sizing of outline.

### ISSUE THREAD

**Issue by ILOVEPIE** [SABRE-JS/SABRE.js#15]
We need to come up with and implement a way of doing axis dependent sizing of the outline of text and shapes in `canvas-2d-text-renderer.js` and `canvas-2d-shape-renderer.js`.

**Comment by ILOVEPIE** [comment]
A good starting point for this would be looking at how outline is handled currently, which is doing a stroke and then cutting out the inner part. Try looking at a canvas 2D tutorial and see if you can figure out a way to make it so you can stretch the y axis of an outline by a specific amount up and down and filling in the inside of the stretched text then cutting out the un-stretched text from it.
See https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation and https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/scale for reference.

**Comment by ILOVEPIE** [comment]
The files you would need to be modifying are canvas-2d-text-renderer.js and canvas-2d-shape-renderer.js, both are very similar.

**Comment by GeraAlcantara** [comment]
Thank for the opportunity to work on this
