### ISSUE TITLE
Implement documentation on font loading using css font loading api.

### ISSUE THREAD

**Issue by ILOVEPIE** [SABRE-JS/SABRE.js#2]
Implement font selection using CSS font loading API and a CSS font loading API polyfill using @font-face and offscreen text to force loading the fonts.

**Comment by ILOVEPIE** [comment]
the font function should just take the name of the font
and then load it the name can either be a filename or a font family

**Comment by roshaan005** [comment]
can I work on this? pls guide me a little

**Comment by ILOVEPIE** [comment]
I would suggest trying your hand at issue #15, i've added some additional instructions that may be helpful with that one. This issue is already almost completed by someone else.
