### ISSUE TITLE
Create unit tests for src/subtitle-event.js that cover the basic functionality of this file.

### ISSUE THREAD

**Issue by ILOVEPIE** [SABRE-JS/SABRE.js#22]
We need unit tests for `src/subtitle-event.js` following a similar style to the ones for `src/color.js` which may be found in `src/__tests__/color.test.js`

**Comment by eLeontev** [comment]
I'll take care about this task. The same as in previous style/style-override tests only setters/getters tests.
I will try to prepare the PR till the end of the week.

ps. feel free to assign the task to me

**Comment by ILOVEPIE** [comment]
fixed by #29
