### ISSUE TITLE
Add support for the browser debugging tools by adding function names in addition to the variable names.

### ISSUE THREAD

**Issue by ILOVEPIE** [SABRE-JS/SABRE.js#92]
This is a simple change, we need someone to go through and change the functions like so:
```js
     _parseTime: {
        /**
         * Parses a string into a time
         * @param {string} timestring the string containing the time.
         * @return {number} time in seconds.
         */
        value: function (timestring) {
            let array = timestring.split(":");
            let time = 0;
            for (let i = 0; i < array.length; i++) {
                if (i !== array.length - 1) {
                    time += global.parseInt(array[i], 10);
                    time *= 60;
                } else {
                    time += global.parseFloat(array[i]);
                }
            }
            return time;
        },
        writable: false
    },
```
becomes:
```js
     _parseTime: {
        /**
         * Parses a string into a time
         * @param {string} timestring the string containing the time.
         * @return {number} time in seconds.
         */
        value: function _parseTime (timestring) {
            let array = timestring.split(":");
            let time = 0;
            for (let i = 0; i < array.length; i++) {
                if (i !== array.length - 1) {
                    time += global.parseInt(array[i], 10);
                    time *= 60;
                } else {
                    time += global.parseFloat(array[i]);
                }
            }
            return time;
        },
        writable: false
    },
```
We need to add the variable names to the functions so the debuggers can identify them.

**Comment by Ayushias0203** [comment]
@ILOVEPIE I would like to work on this issue, could you please assign this to me.

**Comment by ILOVEPIE** [comment]
@Ayushias0203 I'm going to leave the assignment of this issue open as it's a lot of changes to do, I would honestly suggest posting here which files you plan on doing the changes for. Other people can then do the files you don't.

**Comment by ILOVEPIE** [comment]
These changes only apply to code in the ``src`` folder, excluding the ``__tests__`` folder inside it.

**Comment by ILOVEPIE** [comment]
I will be tagging PRs for this issue with ``hacktoberfest-accepted`` so that you get credit for it, but I will only do that for 1 PR per contributor for this specific issue, you can't break up your changes into multiple PRs and get credit for multiple.

**Comment by Ayushias0203** [comment]
@ILOVEPIE I would like to make changes in scheduler.js file.

**Comment by ILOVEPIE** [comment]
> @ILOVEPIE I would like to make changes in scheduler.js file.

That's the smallest file in the project. I would suggest at least doing canvas-2d-shape-renderer.js as well it's a little bigger but still fairly small.

**Comment by ILOVEPIE** [comment]
@Ayushias0203 or shader.js that's also not that big.

**Comment by ILOVEPIE** [comment]
> @ILOVEPIE I will make changes in shader.js file as well along with scheduler.js file.

@Ayushias0203 thanks.
